{
	"version": 1480266123,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/cabeca-sheet0.png",
		"images/cabeca-sheet1.png",
		"images/corpo-sheet0.png",
		"images/filhote-sheet0.png",
		"images/filhote-sheet1.png",
		"images/filhote-sheet2.png",
		"images/grama-sheet0.png",
		"images/spritefont.png",
		"images/tiledbackground.png",
		"images/bgprincipal-sheet0.png",
		"images/botaoiniciar-sheet0.png",
		"images/logo-sheet0.png",
		"images/casa-sheet0.png",
		"images/hidrante-sheet0.png",
		"images/carro-sheet0.png",
		"images/correio-sheet0.png",
		"images/cerca-sheet0.png",
		"images/delegacia-sheet0.png",
		"media/game-over.ogg",
		"media/musica-tema-old.ogg",
		"media/latido.ogg",
		"media/8bit dogsong - undertale.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}